SoC: Fix stubs.c compile fail in RT-Thread Repo
No longer define _DEFAULT_SOURCE in stubs.c to avoid compile fail using rt-thread repo

rt-thread itself implement many include headers in components/libc/compilers folder

CC build\packages\nuclei_sdk-latest\SoC\evalsoc\Common\Source\Stubs\newlib\stubs.o
In file included from C:\Work\Code\rt-thread\components\libc\compilers\common\include/sys/time.h:18,
                 from C:\Work\Code\rt-thread\components\libc\compilers\common\include/sys/select.h:17,
                 from C:/Software/NucleiStudio/toolchain/gcc/riscv64-unknown-elf/include/sys/types.h:50,
                 from C:\Work\Code\rt-thread\components\libc\compilers\common\include/sys/unistd.h:16,
                 from C:\Work\Code\rt-thread\components\libc\compilers\common\include/unistd.h:10,
                 from packages\nuclei_sdk-latest\SoC\evalsoc\Common\Source\Stubs\newlib\stubs.c:9:
C:/Software/NucleiStudio/toolchain/gcc/riscv64-unknown-elf/include/time.h:56:1: error: unknown type name 'clock_t'
   56 | clock_t    clock (void);
      | ^~~~~~~
C:/Software/NucleiStudio/toolchain/gcc/riscv64-unknown-elf/include/time.h:33:1: note: 'clock_t' is defined in header '<time.h>'; this is probably fixable by adding '#include <time.h>'
   32 | #include <sys/_locale.h>
  +++ |+#include <time.h>
   33 | #endif
C:\Work\Code\rt-thread\components\libc\compilers\common\include/sys/time.h:51:5: error: unknown type name 'suseconds_t'
   51 |     suseconds_t tv_usec;    /* and microseconds */
      |     ^~~~~~~~~~~
scons: *** [build\packages\nuclei_sdk-latest\SoC\evalsoc\Common\Source\Stubs\newlib\stubs.o] Error 1
scons: building terminated because of errors.

Signed-off-by: Huaqi Fang <578567190@qq.com>