tools/nsdk_cli: skip process if the value is None
below will occurs when dhrystone_v2.2 can't get "csv,xx,xx" pring
because of timeout in qemu

    csvdict[cfg][apptype][appsubtype]["value"].update(appresult[cfg]["result"]["value"])
TypeError: 'NoneType' object is not iterable

Trying 50000 runs through Dhrystone:
Measured time too small to obtain meaningful results

Trying 500000 runs through Dhrystone:
Measured time too small to obtain meaningful results

Trying 5000000 runs through Dhrystone:

Signed-off-by: dongyongtao <dongyongtao@nucleisys.com>