SoC: add _DEFAULT_SOURCE definition for POSIX compliance in stubs.c
If your compiler option use a different c standard such as c99/c11/c23 whihc dont support BSD/GNU extension required by stubs.c, define _DEFAULT_SOURCE is a good way to let compiler not report error

such as below

../../../SoC/evalsoc/Common/Source/Stubs/newlib/stubs.c:262:9: error: implicit declaration of function 'TIMEVAL_TO_TIMESPEC' [-Wimplicit-function-declaration]
  262 |         TIMEVAL_TO_TIMESPEC(&tv, tp);
      |         ^~~~~~~~~~~~~~~~~~~