application: dont pass -flto option for demo_eclic_stress
-flto option by default should not be enabled, it will make
build with STDCLIB=newlib_full link fail with following issue

Linking    :  demo_eclic_stress.elf
/home/riscv/nuclei/gcc/bin/../lib/gcc/riscv64-unknown-elf/14.2.1/../../../../riscv64-unknown-elf/bin/ld: /home/riscv/nuclei/gcc/bin/../lib/gcc/riscv64-unknown-elf/14.2.1/../../../../riscv64-unknown-elf/lib/rv32imafdc_zaamo_zalrsc/ilp32d/libc.a(libc_a-signalr.o): in function `_kill_r':
(.text._kill_r+0x18): undefined reference to `_kill'
/home/riscv/nuclei/gcc/bin/../lib/gcc/riscv64-unknown-elf/14.2.1/../../../../riscv64-unknown-elf/bin/ld: /home/riscv/nuclei/gcc/bin/../lib/gcc/riscv64-unknown-elf/14.2.1/../../../../riscv64-unknown-elf/lib/rv32imafdc_zaamo_zalrsc/ilp32d/libc.a(libc_a-signalr.o): in function `_getpid_r':
(.text._getpid_r+0x0): undefined reference to `_getpid'
collect2: error: ld returned 1 exit status

If you want to remove this issue, you can pass extra compiler option
`-u _getpid -u _kill` to make sure this symbol not removed by force,
since it is defined in newlib/stubs.c

Signed-off-by: Huaqi Fang <578567190@qq.com>